import matplotlib.pyplot as plt

plt.style.use('bmh')

######################################## 1. CIENCIAS NATURALES #########################################################
fig, ax = plt.subplots(4,2)
fig.subplots_adjust(hspace=.5)
fig.set_size_inches(4,6)
fig.suptitle('1. CIENCIAS NATURALES (ACADÉMICAS)', fontsize=11)
ax[0,0].plot(Matematicas_AC["Ranking_ANID"], Matematicas_AC["Puntaje_ANID"], label='Puntaje')
ax[0,0].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[0,0].set_title("1.01 Matemáticas", fontsize='small')
ax[0,0].legend(loc='upper right', fontsize='small')
#ax[0,0].set_xlabel('X axes label')
#ax[0,0].set_ylabel('Y axes label')
ax[0,0].grid(True)
ax[0,0].set_xlim([0,1000])
#ax[0,0].set_ylim([0,])
ax[0,1].plot(Computacion_AC["Ranking_ANID"], Computacion_AC["Puntaje_ANID"], label='Puntaje')
ax[0,1].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[0,1].set_title("1.02 Computación y Ciencias de la informática", fontsize='small')
ax[0,1].legend(loc='upper right', fontsize='small')
#ax[0,1].set_xlabel('X axes label')
#ax[0,1].set_ylabel('Y axes label')
ax[0,1].grid(True)
ax[0,1].set_xlim([0,1000])
#ax[0,1].set_ylim([0,1000])
ax[1,0].plot(Fisica_AC["Ranking_ANID"], Fisica_AC["Puntaje_ANID"], label='Puntaje')
ax[1,0].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[1,0].set_title("1.03 Ciencias Físicas y Astronomía", fontsize='small')
ax[1,0].legend(loc='upper right', fontsize='small')
#ax[1,0].set_xlabel('X axes label')
#ax[1,0].set_ylabel('Y axes label')
ax[1,0].grid(True)
ax[1,0].set_xlim([0,1000])
#ax[1,0].set_ylim([0,1000])
ax[1,1].plot(Quimica_AC["Ranking_ANID"], Quimica_AC["Puntaje_ANID"], label='Puntaje')
ax[1,1].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[1,1].set_title("1.04 Ciencias Químicas", fontsize='small')
ax[1,1].legend(loc='upper right', fontsize='small')
#ax[1,1].set_xlabel('X axes label')
#ax[1,1].set_ylabel('Y axes label')
ax[1,1].grid(True)
ax[1,1].set_xlim([0,1000])
#ax[1,1].set_ylim([0,1000])
ax[2,0].plot(Tierra_AC["Ranking_ANID"], Tierra_AC["Puntaje_ANID"], label='Puntaje')
ax[2,0].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[2,0].set_title("1.05 Ciencias de la Tierra y Medioambientales", fontsize='small')
ax[2,0].legend(loc='upper right', fontsize='small')
#ax[2,0].set_xlabel('X axes label')
#ax[2,0].set_ylabel('Y axes label')
ax[2,0].grid(True)
ax[2,0].set_xlim([0,1000])
#ax[2,0].set_ylim([0,1000])
ax[2,1].plot(Biologicas_AC["Ranking_ANID"], Biologicas_AC["Puntaje_ANID"], label='Puntaje')
ax[2,1].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[2,1].set_title("1.06 Ciencias Biológicas", fontsize='small')
ax[2,1].legend(loc='upper right', fontsize='small')
#ax[2,1].set_xlabel('X axes label')
#ax[2,1].set_ylabel('Y axes label')
ax[2,1].grid(True)
ax[2,1].set_xlim([0,1000])
#ax[2,1].set_ylim([0,1000])
ax[3,0].plot(Otras_naturales_AC["Ranking_ANID"], Otras_naturales_AC["Puntaje_ANID"], label='Puntaje')
ax[3,0].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[3,0].set_title("1.07 Otras Ciencias Naturales", fontsize='small')
ax[3,0].legend(loc='upper right', fontsize='small')
#ax[3,0].set_xlabel('X axes label')
#ax[3,0].set_ylabel('Y axes label')
ax[3,0].grid(True)
ax[3,0].set_xlim([0,1000])
#ax[3,0].set_ylim([0,1000])
fig.delaxes(ax[3,1])

######################################## 2. INGENIERÍA Y TECNOLOGÍA ####################################################
fig, ax = plt.subplots(6,2)
fig.subplots_adjust(hspace=.5)
fig.set_size_inches(4,6)
fig.suptitle('2. INGENIERÍA Y TECNOLOGÍA (ACADÉMICAS)', fontsize=11)

ax[0,0].plot(Civil_AC["Ranking_ANID"], Civil_AC["Puntaje_ANID"], label='Puntaje')
ax[0,0].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[0,0].set_title("2.01 Ingeniería Civil", fontsize='small')
ax[0,0].legend(loc='upper right', fontsize='small')
#ax[0,0].set_xlabel('X axes label')
#ax[0,0].set_ylabel('Y axes label')
ax[0,0].grid(True)
ax[0,0].set_xlim([0,1000])
#ax[0,0].set_ylim([0,1000])
ax[0,1].plot(Electrica_AC["Ranking_ANID"], Electrica_AC["Puntaje_ANID"], label='Puntaje')
ax[0,1].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[0,1].set_title("2.02 Ingeniería Eléctrica y Electrónica",fontsize='small')
ax[0,1].legend(loc='upper right', fontsize='small')
#ax[0,1].set_xlabel('X axes label')
#ax[0,1].set_ylabel('Y axes label')
ax[0,1].grid(True)
ax[0,1].set_xlim([0,1000])
#ax[0,1].set_ylim([0,1000])
ax[1,0].plot(Mecanica_AC["Ranking_ANID"], Mecanica_AC["Puntaje_ANID"], label='Puntaje')
ax[1,0].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[1,0].set_title("2.03 Ingeniería Mecánica",fontsize='small')
ax[1,0].legend(loc='upper right', fontsize='small')
#ax[1,0].set_xlabel('X axes label')
#ax[1,0].set_ylabel('Y axes label')
ax[1,0].grid(True)
ax[1,0].set_xlim([0,1000])
#ax[1,0].set_ylim([0,1000])
ax[1,1].plot(Ing_Quimica_AC["Ranking_ANID"], Ing_Quimica_AC["Puntaje_ANID"], label='Puntaje')
ax[1,1].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[1,1].set_title("2.04 Ingeniería Química",fontsize='small')
ax[1,1].legend(loc='upper right', fontsize='small')
#ax[1,1].set_xlabel('X axes label')
#ax[1,1].set_ylabel('Y axes label')
ax[1,1].grid(True)
ax[1,1].set_xlim([0,1000])
#ax[1,1].set_ylim([0,1000])
ax[2,0].plot(Ing_Materiales_AC["Ranking_ANID"], Ing_Materiales_AC["Puntaje_ANID"], label='Puntaje')
ax[2,0].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[2,0].set_title("2.05 Ingeniería de Materiales",fontsize='small')
ax[2,0].legend(loc='upper right', fontsize='small')
#ax[2,0].set_xlabel('X axes label')
#ax[2,0].set_ylabel('Y axes label')
ax[2,0].grid(True)
ax[2,0].set_xlim([0,1000])
#ax[2,0].set_ylim([0,1000])
ax[2,1].plot(Ing_Medica_AC["Ranking_ANID"], Ing_Medica_AC["Puntaje_ANID"], label='Puntaje')
ax[2,1].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[2,1].set_title("2.06 Ingeniería Médica",fontsize='small')
ax[2,1].legend(loc='upper right', fontsize='small')
#ax[2,1].set_xlabel('X axes label')
#ax[2,1].set_ylabel('Y axes label')
ax[2,1].grid(True)
ax[2,1].set_xlim([0,1000])
#ax[2,1].set_ylim([0,1000])
ax[3,0].plot(Ing_Medioambiental_AC["Ranking_ANID"], Ing_Medioambiental_AC["Puntaje_ANID"], label='Puntaje')
ax[3,0].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[3,0].set_title("2.07 Ingeniería Medioambiental",fontsize='small')
ax[3,0].legend(loc='upper right', fontsize='small')
#ax[3,0].set_xlabel('X axes label')
#ax[3,0].set_ylabel('Y axes label')
ax[3,0].grid(True)
ax[3,0].set_xlim([0,1000])
#ax[3,0].set_ylim([0,])
ax[3,1].plot(Biotec_Medioambiental_AC["Ranking_ANID"], Biotec_Medioambiental_AC["Puntaje_ANID"], label='Puntaje')
ax[3,1].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[3,1].set_title("2.08 Biotecnología Medioambiental",fontsize='small')
ax[3,1].legend(loc='upper right', fontsize='small')
#ax[3,1].set_xlabel('X axes label')
#ax[3,1].set_ylabel('Y axes label')
ax[3,1].grid(True)
ax[3,1].set_xlim([0,1000])
#ax[3,1].set_ylim([0,1000])
ax[4,0].plot(Biotec_Industrial_AC["Ranking_ANID"], Biotec_Industrial_AC["Puntaje_ANID"], label='Puntaje')
ax[4,0].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[4,0].set_title("2.09 Biotecnología Industrial",fontsize='small')
ax[4,0].legend(loc='upper right', fontsize='small')
#ax[4,0].set_xlabel('X axes label')
#ax[4,0].set_ylabel('Y axes label')
ax[4,0].grid(True)
ax[4,0].set_xlim([0,1000])
#ax[4,0].set_ylim([0,1000])
ax[4,1].plot(Nanotecnologia_AC["Ranking_ANID"], Nanotecnologia_AC["Puntaje_ANID"], label='Puntaje')
ax[4,1].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[4,1].set_title("2.10 Nanotecnología",fontsize='small')
ax[4,1].legend(loc='upper right', fontsize='small')
#ax[4,1].set_xlabel('X axes label')
#ax[4,1].set_ylabel('Y axes label')
ax[4,1].grid(True)
ax[4,1].set_xlim([0,1000])
#ax[4,1].set_ylim([0,1000])
ax[5,0].plot(Otras_Ingenierias_AC["Ranking_ANID"], Otras_Ingenierias_AC["Puntaje_ANID"], label='Puntaje')
ax[5,0].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[5,0].set_title("2.11 Otras Ingenierías y Tecnologías",fontsize='small')
ax[5,0].legend(loc='upper right', fontsize='small')
#ax[5,0].set_xlabel('X axes label')
#ax[5,0].set_ylabel('Y axes label')
ax[5,0].grid(True)
ax[5,0].set_xlim([0,1000])
#ax[5,0].set_ylim([0,1000])
fig.delaxes(ax[5,1])


##################################### 3. CIENCIAS MÉDICAS Y DE LA SALUD ################################################
fig, ax = plt.subplots(2,2)
fig.subplots_adjust(hspace=.5)
fig.set_size_inches(4,6)
fig.suptitle('3. CIENCIAS MÉDICAS Y DE LA SALUD (ACADÉMICAS)', fontsize=11)
ax[0,0].plot(Medicina_Basica_AC["Ranking_ANID"], Medicina_Basica_AC["Puntaje_ANID"], label='Puntaje')
ax[0,0].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[0,0].set_title("3.01 Medicina Básica", fontsize='small')
ax[0,0].legend(loc='upper right', fontsize='small')
#ax[0,0].set_xlabel('X axes label')
#ax[0,0].set_ylabel('Y axes label')
ax[0,0].grid(True)
ax[0,0].set_xlim([0,1000])
#ax[0,0].set_ylim([0,])
ax[0,1].plot(Medicina_Clinica_AC["Ranking_ANID"], Medicina_Clinica_AC["Puntaje_ANID"], label='Puntaje')
ax[0,1].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[0,1].set_title("3.02 Medicina Clínica", fontsize='small')
ax[0,1].legend(loc='upper right', fontsize='small')
#ax[0,1].set_xlabel('X axes label')
#ax[0,1].set_ylabel('Y axes label')
ax[0,1].grid(True)
ax[0,1].set_xlim([0,1000])
#ax[0,1].set_ylim([0,1000])
ax[1,0].plot(Ciencias_Salud_AC["Ranking_ANID"], Ciencias_Salud_AC["Puntaje_ANID"], label='Puntaje')
ax[1,0].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[1,0].set_title("3.03 Ciencias de la Salud", fontsize='small')
ax[1,0].legend(loc='upper right', fontsize='small')
#ax[1,0].set_xlabel('X axes label')
#ax[1,0].set_ylabel('Y axes label')
ax[1,0].grid(True)
ax[1,0].set_xlim([0,1000])
#ax[1,0].set_ylim([0,1000])
fig.delaxes(ax[1,1])


############################################ 4. CIENCIAS AGRÍCOLAS #####################################################
fig, ax = plt.subplots(2,2)
fig.subplots_adjust(hspace=.5)
fig.set_size_inches(4,6)
fig.suptitle('4. CIENCIAS AGRÍCOLAS (ACADÉMICAS)', fontsize=11)
ax[0,0].plot(Agricultura_AC["Ranking_ANID"], Agricultura_AC["Puntaje_ANID"], label='Puntaje')
ax[0,0].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[0,0].set_title("4.01 Agricultura, Silvicultura y Pesca", fontsize='small')
ax[0,0].legend(loc='upper right', fontsize='small')
#ax[0,0].set_xlabel('X axes label')
#ax[0,0].set_ylabel('Y axes label')
ax[0,0].grid(True)
ax[0,0].set_xlim([0,1000])
#ax[0,0].set_ylim([0,])
ax[0,1].plot(Ciencias_Animales_AC["Ranking_ANID"], Ciencias_Animales_AC["Puntaje_ANID"], label='Puntaje')
ax[0,1].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[0,1].set_title("4.02 Ciencias Animales y de la Leche", fontsize='small')
ax[0,1].legend(loc='upper right', fontsize='small')
#ax[0,1].set_xlabel('X axes label')
#ax[0,1].set_ylabel('Y axes label')
ax[0,1].grid(True)
ax[0,1].set_xlim([0,1000])
#ax[0,1].set_ylim([0,1000])
ax[1,0].plot(Ciencias_Veterinarias_AC["Ranking_ANID"], Ciencias_Veterinarias_AC["Puntaje_ANID"], label='Puntaje')
ax[1,0].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[1,0].set_title("4.03 Ciencias Veterinarias", fontsize='small')
ax[1,0].legend(loc='upper right', fontsize='small')
#ax[1,0].set_xlabel('X axes label')
#ax[1,0].set_ylabel('Y axes label')
ax[1,0].grid(True)
ax[1,0].set_xlim([0,1000])
#ax[1,0].set_ylim([0,1000])
ax[1,1].plot(Otras_Agricolas_AC["Ranking_ANID"], Otras_Agricolas_AC["Puntaje_ANID"], label='Puntaje')
ax[1,1].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[1,1].set_title("4.05 Otras Ciencias Agrícolas", fontsize='small')
ax[1,1].legend(loc='upper right', fontsize='small')
#ax[1,1].set_xlabel('X axes label')
#ax[1,1].set_ylabel('Y axes label')
ax[1,1].grid(True)
ax[1,1].set_xlim([0,1000])
#ax[1,1].set_ylim([0,1000])



############################################ 5. CIENCIAS SOCIALES ######################################################
fig, ax = plt.subplots(5,2)
fig.subplots_adjust(hspace=.5)
fig.set_size_inches(4,6)
fig.suptitle('5. CIENCIAS SOCIALES (ACADÉMICAS)', fontsize=11)

ax[0,0].plot(Psicologia_AC["Ranking_ANID"], Psicologia_AC["Puntaje_ANID"], label='Puntaje')
ax[0,0].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[0,0].set_title("5.01 Psicología", fontsize='small')
ax[0,0].legend(loc='upper right', fontsize='small')
#ax[0,0].set_xlabel('X axes label')
#ax[0,0].set_ylabel('Y axes label')
ax[0,0].grid(True)
ax[0,0].set_xlim([0,1000])
#ax[0,0].set_ylim([0,1000])
ax[0,1].plot(Economia_AC["Ranking_ANID"], Economia_AC["Puntaje_ANID"], label='Puntaje')
ax[0,1].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[0,1].set_title("5.02 Economía y Negocios",fontsize='small')
ax[0,1].legend(loc='upper right', fontsize='small')
#ax[0,1].set_xlabel('X axes label')
#ax[0,1].set_ylabel('Y axes label')
ax[0,1].grid(True)
ax[0,1].set_xlim([0,1000])
#ax[0,1].set_ylim([0,1000])
ax[1,0].plot(Educacion_AC["Ranking_ANID"], Educacion_AC["Puntaje_ANID"], label='Puntaje')
ax[1,0].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[1,0].set_title("5.03 Ciencias de la Educación",fontsize='small')
ax[1,0].legend(loc='upper right', fontsize='small')
#ax[1,0].set_xlabel('X axes label')
#ax[1,0].set_ylabel('Y axes label')
ax[1,0].grid(True)
ax[1,0].set_xlim([0,1000])
#ax[1,0].set_ylim([0,1000])
ax[1,1].plot(Sociologia_AC["Ranking_ANID"], Sociologia_AC["Puntaje_ANID"], label='Puntaje')
ax[1,1].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[1,1].set_title("5.04 Sociología",fontsize='small')
ax[1,1].legend(loc='upper right', fontsize='small')
#ax[1,1].set_xlabel('X axes label')
#ax[1,1].set_ylabel('Y axes label')
ax[1,1].grid(True)
ax[1,1].set_xlim([0,1000])
#ax[1,1].set_ylim([0,1000])
ax[2,0].plot(Leyes_AC["Ranking_ANID"], Leyes_AC["Puntaje_ANID"], label='Puntaje')
ax[2,0].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[2,0].set_title("5.05 Leyes",fontsize='small')
ax[2,0].legend(loc='upper right', fontsize='small')
#ax[2,0].set_xlabel('X axes label')
#ax[2,0].set_ylabel('Y axes label')
ax[2,0].grid(True)
ax[2,0].set_xlim([0,1000])
#ax[2,0].set_ylim([0,1000])
ax[2,1].plot(Ciencias_Politicas_AC["Ranking_ANID"], Ciencias_Politicas_AC["Puntaje_ANID"], label='Puntaje')
ax[2,1].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[2,1].set_title("5.06 Ciencias Políticas",fontsize='small')
ax[2,1].legend(loc='upper right', fontsize='small')
#ax[2,1].set_xlabel('X axes label')
#ax[2,1].set_ylabel('Y axes label')
ax[2,1].grid(True)
ax[2,1].set_xlim([0,1000])
#ax[2,1].set_ylim([0,1000])
ax[3,0].plot(Geografia_AC["Ranking_ANID"], Geografia_AC["Puntaje_ANID"], label='Puntaje')
ax[3,0].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[3,0].set_title("5.07 Geografía Social y Económica",fontsize='small')
ax[3,0].legend(loc='upper right', fontsize='small')
#ax[3,0].set_xlabel('X axes label')
#ax[3,0].set_ylabel('Y axes label')
ax[3,0].grid(True)
ax[3,0].set_xlim([0,1000])
#ax[3,0].set_ylim([0,])
ax[3,1].plot(Periodismo_AC["Ranking_ANID"], Periodismo_AC["Puntaje_ANID"], label='Puntaje')
ax[3,1].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[3,1].set_title("5.08 Periodismo y Comunicaciones",fontsize='small')
ax[3,1].legend(loc='upper right', fontsize='small')
#ax[3,1].set_xlabel('X axes label')
#ax[3,1].set_ylabel('Y axes label')
ax[3,1].grid(True)
ax[3,1].set_xlim([0,1000])
#ax[3,1].set_ylim([0,1000])
ax[4,0].plot(Otras_Sociales_AC["Ranking_ANID"], Otras_Sociales_AC["Puntaje_ANID"], label='Puntaje')
ax[4,0].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[4,0].set_title("5.09 Otras Ciencias Sociales",fontsize='small')
ax[4,0].legend(loc='upper right', fontsize='small')
#ax[4,0].set_xlabel('X axes label')
#ax[4,0].set_ylabel('Y axes label')
ax[4,0].grid(True)
ax[4,0].set_xlim([0,1000])
#ax[4,0].set_ylim([0,1000])
fig.delaxes(ax[4,1])

############################################### 6. HUMANIDADES #########################################################
fig, ax = plt.subplots(3,2)
fig.subplots_adjust(hspace=.5)
fig.set_size_inches(4,6)
fig.suptitle('6. HUMANIDADES (ACADÉMICAS)', fontsize=11)
ax[0,0].plot(Historia_AC["Ranking_ANID"], Historia_AC["Puntaje_ANID"], label='Puntaje')
ax[0,0].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[0,0].set_title("6.01 Historia y Arqueología", fontsize='small')
ax[0,0].legend(loc='upper right', fontsize='small')
#ax[0,0].set_xlabel('X axes label')
#ax[0,0].set_ylabel('Y axes label')
ax[0,0].grid(True)
ax[0,0].set_xlim([0,1000])
#ax[0,0].set_ylim([0,])
ax[0,1].plot(Idiomas_AC["Ranking_ANID"], Idiomas_AC["Puntaje_ANID"], label='Puntaje')
ax[0,1].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[0,1].set_title("6.02 Idiomas y Literatura", fontsize='small')
ax[0,1].legend(loc='upper right', fontsize='small')
#ax[0,1].set_xlabel('X axes label')
#ax[0,1].set_ylabel('Y axes label')
ax[0,1].grid(True)
ax[0,1].set_xlim([0,1000])
#ax[0,1].set_ylim([0,1000])
ax[1,0].plot(Filosofia_AC["Ranking_ANID"], Filosofia_AC["Puntaje_ANID"], label='Puntaje')
ax[1,0].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[1,0].set_title("6.03 Filosofía, Ética y Religión", fontsize='small')
ax[1,0].legend(loc='upper right', fontsize='small')
#ax[1,0].set_xlabel('X axes label')
#ax[1,0].set_ylabel('Y axes label')
ax[1,0].grid(True)
ax[1,0].set_xlim([0,1000])
#ax[1,0].set_ylim([0,1000])
ax[1,1].plot(Arte_AC["Ranking_ANID"], Arte_AC["Puntaje_ANID"], label='Puntaje')
ax[1,1].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[1,1].set_title("6.04 Arte", fontsize='small')
ax[1,1].legend(loc='upper right', fontsize='small')
#ax[1,1].set_xlabel('X axes label')
#ax[1,1].set_ylabel('Y axes label')
ax[1,1].grid(True)
ax[1,1].set_xlim([0,1000])
#ax[1,1].set_ylim([0,1000])
ax[2,0].plot(Otras_Humanidades_AC["Ranking_ANID"], Otras_Humanidades_AC["Puntaje_ANID"], label='Puntaje')
ax[2,0].axvline(x=150, ymin=0, ymax=5, color='gray', linestyle='--', linewidth=1, label= 'Posición 150')
ax[2,0].set_title("6.05 Otras Humanidades", fontsize='small')
ax[2,0].legend(loc='upper right', fontsize='small')
#ax[2,0].set_xlabel('X axes label')
#ax[2,0].set_ylabel('Y axes label')
ax[2,0].grid(True)
ax[2,0].set_xlim([0,1000])
#ax[2,0].set_ylim([0,1000])
fig.delaxes(ax[2,1])

############################################### FIN #########################################################
